# Basic
title: Carol
subtitle: Stay hungry stay foolish
#welcome_message: Welcome
description: Carol的前端修行
#creator: <a href="http://onev.cat">@beginnercarol</a>

url: "https://github.com/beginnercarol"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    #- {title: Projects, description: My Projects, url: 'https://github.com/beginnercarol'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    #disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    #weibo: beginnercarol
    github: beginnercarol
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail:  carolpangyaoyao@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
